### ISSUE TITLE
Maybe need a advanced localization system.

### ISSUE THREAD

**Issue by crafteverywhere** [FrogCraft/FrogCraft#1]
Maybe you need a advanced localization system just like which buildcraft have.

Then you can manage it easily and allow the foreigners translate this to their own language.

Only a other probelm is that maybe you should make it works even without Gregtech,since not everybody will install that but may want to try ur mod.

BTW,I'm glad to see a nice mod created by Chinese.

**Comment by rikka0w0** [comment]
Thanks for your suggestion!

Indepence from GregTech is hard,beacause my mod need a lot of raw materials that gregtech has, as my mod currently is small, so I have to adapt to larger mods, gregtech won't do ore unification for me and I have to do it myself, so much work ....QAQ

And yesterday I tried to undate to 1.6.2 but found the liquid system is replaced by the new fluid system, 30% of my code need to be rewritten ahhhhhhhhh

------------------ 原始邮件 ------------------
发件人: "crafteverywhere"notifications@github.com;
发送时间: 2013年7月13日(星期六) 晚上8:40
收件人: "FrogCraft/FrogCraft"FrogCraft@noreply.github.com; 

主题: [FrogCraft] Maybe need a advanced localization system. (#1)

Maybe you need a advanced localization system just like which buildcraft have.

Then you can manage it easily and allow the foreigners translate this to their own language.

Only a other probelm is that maybe you should make it works even without Gregtech,since not everybody will install that but may want to try ur mod.

BTW,I'm glad to see a nice mod created by Chinese.

**Comment by acaly** [comment]
A localization system is easy. Maybe we should consider the suggestion after upgrading to 1.6.2?

**Comment by rikka0w0** [comment]
Yes, that wll be a bug job, but we have a team right now and I feel cnfident!

**Comment by Vexatos** [comment]
I think this can be closed since the mod is now translatable...
